services:
  lucid_driver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/arena_camera_ros2
    network_mode: host
    entrypoint: ["/bin/bash", "-c", " source /opt/ros/eloquent/setup.bash && source ./install/setup.bash && ros2 run arena_camera_node start --ros-args -p serial:=${SERIAL_NUMBER:-240302225}"]
