version: "3.2"
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/arena_camera_ros2

    network_mode: host
    entrypoint: ros2 run arena_camera_node start --ros-args -p serial:="${SERIAL_NUMBER:240302225}"
